### ISSUE TITLE
Plugin gives an error with my Sony Bravia X7400H

### ISSUE THREAD

**Issue by gauravkej** [SeydX/homebridge-bravia-tvos#150]
First of all, I must say what an amazing piece of work. I just entered the Homebridge ecosystem (last weekend) and I loved all the plugins that you have developed so far. Thank you for all the hard work! 

I get the following 2 types of Errors when trying to use the plugin with my Sony Bravia X74H series (or X7400H). 

Error Log from Homebridge:
**During Bootup**

>[20/07/2021, 12:14:11] [BraviaTVOS] BraviaTVW: An error occured during getting television state!
[20/07/2021, 12:14:11] [BraviaTVOS] Error: getPlayingContentInfo
    at exports.request (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/request.js:80:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/service.js:89:12)
    at Handler.getTelevisionState (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:16:24)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:458:7) {
  title: 'Invalid Response',
  code: 12,
  soap: {},
  url: 'http://192.168.1.53/sony/avContent'
}

**During Runtime**

> [20/07/2021, 12:14:21] [BraviaTVOS] [DEBUG] BraviaTVW: Polling API...
[20/07/2021, 12:14:21] [BraviaTVOS] BraviaTVW: An error occured during getting television state!
[20/07/2021, 12:14:21] [BraviaTVOS] Error: getPlayingContentInfo
    at exports.request (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/request.js:80:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ServiceProtocol.invoke (/usr/local/lib/node_modules/homebridge-bravia-tvos/node_modules/@seydx/bravia/lib/service.js:89:12)
    at Handler.getTelevisionState (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:16:24)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-bravia-tvos/src/accessories/accessory.handler.js:458:7) {
  title: 'Invalid Response',
  code: 12,
  soap: {},
  url: 'http://192.168.1.53/sony/avContent'
}

For Debugging, I tried manually checking what all APIs are supported by the model that I have using the "getSupportedApiInfo()" for the avContent service and here's the result:

> {

    "method": "getSupportedApiInfo",
    "id": 5,
    "params": [{"services": [
        "system",
        "avContent",
        "appControl"
    ]}],
    "version": "1.0"
}

And I got the following response. 

>  {

    "result": [
        [
            {
                "service": "system",
                "protocols": [
                    "xhrpost:jsonizer"
                ],
                "apis": [
                    {
                        "name": "getMethodTypes",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "getVersions",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "requestReboot",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "generic"
                            }
                        ]
                    },
                    {
                        "name": "setPowerStatus",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "generic"
                            }
                        ]
                    },
                    {
                        "name": "getInterfaceInformation",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "getNetworkSettings",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "generic"
                            }
                        ]
                    },
                    {
                        "name": "getPowerStatus",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "getCurrentTime",
                        "versions": [
                            {
                                "version": "1.0"
                            },
                            {
                                "version": "1.1"
                            }
                        ]
                    },
                    {
                        "name": "getSystemInformation",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "private"
                            }
                        ]
                    },
                    {
                        "name": "getRemoteControllerInfo",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    }
                ]
            },
            {
                "service": "appControl",
                "protocols": [
                    "xhrpost:jsonizer"
                ],
                "apis": [
                    {
                        "name": "getMethodTypes",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "getVersions",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "setActiveApp",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "generic"
                            }
                        ]
                    },
                    {
                        "name": "getApplicationList",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "private"
                            }
                        ]
                    }
                ]
            },
            {
                "service": "avContent",
                "protocols": [
                    "xhrpost:jsonizer"
                ],
                "apis": [
                    {
                        "name": "getMethodTypes",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "getVersions",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "getContentList",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "private"
                            }
                        ]
                    },
                    {
                        "name": "getSchemeList",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "getSourceList",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    },
                    {
                        "name": "setPlayContent",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "generic"
                            }
                        ]
                    },
                    {
                        "name": "getContentCount",
                        "versions": [
                            {
                                "version": "1.0",
                                "authLevel": "private"
                            }
                        ]
                    },
                    {
                        "name": "getCurrentExternalInputsStatus",
                        "versions": [
                            {
                                "version": "1.0"
                            }
                        ]
                    }
                ]
            }
        ]
    ],
    "id": 5
}

**My thoughts so far:**
It appears that my TV model doesn't support "getPlayingContentInfo()" and hence the plugin fails to recognize the capabilities. If we can disable or bypass the getPlayingCintentinfo section then we should be able to still control and use the TV for all the other functionalities. 

It'll be really helpful if you can please look into this and implement a fix for this. I'll be happy to provide whatever logs or info that is required for debugging this.

**Comment by Paden** [comment]
Great plugin, guys! Same issue with the x750H. I cannot get Applications/Custom Commands to work as well. I am guessing it has to do with this erroring out.

**Comment by SeydX** [comment]
Added/Fixed in v5.0.6 (beta)

`sudo npm i -g homebridge-bravia-tvos@beta`

**Comment by Paden** [comment]
Thanks, @SeydX! Looking forwarded to this being released

**Comment by SeydX** [comment]
@Paden 

can you test it pls, maybe i need to fix some more stuff before release it

**Comment by Paden** [comment]
The error has gone away but I am still unable to switch Applications via HomeKit

**Comment by SeydX** [comment]
Yeah they are only visible if you enabled debug. 

What kind of input you try to activate? App? Channel? Command?

**Comment by Paden** [comment]
App

**Comment by SeydX** [comment]
@Paden 

it seems your tv also doesnt support the required service method „setActiveApp“ to controll Applications.

can u try to debug your tv like the OP

```
"method": "getSupportedApiInfo",
"id": 5,
"params": [{"services": [
    "system",
    "avContent",
    "appControl"
]}],
"version": "1.0"
```

and can u try to activate a channel or input source (like hdmi) instead of an Application pls

**Comment by Paden** [comment]
![image](https://user-images.githubusercontent.com/264875/134690800-b3dbccb4-4fe8-4d2f-ad51-29a33602c9af.png)
Looks like it doesn't even support `getSupportedApiInfo` -- I'll try the input source a bit later

**Comment by SeydX** [comment]
There is a much simpler method

Install my bravia module globally with:

`sudo npm i -g @seydx/bravia@beta`

and enter following in your terminal

`bravia methods TVIP`

_(eg **bravia methods 192.123.123.12**)_

it should list all available services and methods

**Comment by Paden** [comment]
That was helpful! Oddly enough it does show `setActiveApp`

```JSON
[
  {
    "service": "accessControl",
    "methods": []
  },
  {
    "service": "appControl",
    "methods": [
      [
        {
          "method": "getApplicationList",
          "version": "1.0"
        },
        {
          "method": "setActiveApp",
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "version": "1.0"
        }
      ]
    ]
  },
  {
    "service": "audio",
    "methods": [
      {
        "method": "getVolumeInformation",
        "version": "1.0"
      },
      {
        "method": "setAudioMute",
        "version": "1.0"
      },
      {
        "method": "setAudioVolume",
        "version": "1.0"
      },
      {
        "method": "getMethodTypes",
        "version": "1.0"
      },
      {
        "method": "getVersions",
        "version": "1.0"
      },
      {
        "method": "setAudioVolume",
        "version": "1.2"
      }
    ]
  },
  {
    "service": "avContent",
    "methods": [
      [
        {
          "method": "getContentCount",
          "version": "1.0"
        },
        {
          "method": "getContentList",
          "version": "1.0"
        },
        {
          "method": "getCurrentExternalInputsStatus",
          "version": "1.0"
        },
        {
          "method": "getSchemeList",
          "version": "1.0"
        },
        {
          "method": "getSourceList",
          "version": "1.0"
        },
        {
          "method": "setPlayContent",
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "version": "1.0"
        }
      ]
    ]
  },
  {
    "service": "browser",
    "methods": []
  },
  {
    "service": "cec",
    "methods": []
  },
  {
    "service": "contentshare",
    "methods": []
  },
  {
    "service": "encryption",
    "methods": []
  },
  {
    "service": "guide",
    "methods": [
      [
        {
          "method": "getServiceProtocols",
          "version": "1.0"
        },
        {
          "method": "getSupportedApiInfo",
          "version": "1.0"
        },
        {
          "method": "getMethodTypes",
          "version": "1.0"
        },
        {
          "method": "getVersions",
          "version": "1.0"
        }
      ]
    ]
  },
  {
    "service": "recording",
    "methods": []
  },
  {
    "service": "system",
    "methods": [
      {
        "method": "getCurrentTime",
        "version": "1.0"
      },
      {
        "method": "getInterfaceInformation",
        "version": "1.0"
      },
      {
        "method": "getNetworkSettings",
        "version": "1.0"
      },
      {
        "method": "getPowerStatus",
        "version": "1.0"
      },
      {
        "method": "getRemoteControllerInfo",
        "version": "1.0"
      },
      {
        "method": "getSystemInformation",
        "version": "1.0"
      },
      {
        "method": "requestReboot",
        "version": "1.0"
      },
      {
        "method": "setPowerStatus",
        "version": "1.0"
      },
      {
        "method": "getMethodTypes",
        "version": "1.0"
      },
      {
        "method": "getVersions",
        "version": "1.0"
      },
      {
        "method": "getCurrentTime",
        "version": "1.1"
      }
    ]
  },
  {
    "service": "video",
    "methods": []
  },
  {
    "service": "videoScreen",
    "methods": []
  }
]
```

**Comment by SeydX** [comment]
I will check it thx

**Comment by SeydX** [comment]
@Paden 

can u try latest Beta pls v5.0.6-beta.5

``sudo npm i -g homebridge-bravia-tvos@beta``

**Comment by Paden** [comment]
Same problem
![image](https://user-images.githubusercontent.com/264875/134735243-ccf252ad-4364-498a-9ef6-76ded015f004.png)

**Comment by SeydX** [comment]
Yeah thats because your tv does not support `getPlayingContentInfo`

that was expected and can be muted if you disable `debug`

But how about changing inputs/apps ?

**Comment by SeydX** [comment]
v5.0.6-beta.6 is online

it should show which service method exactly fails

`sudo npm i -g homebridge-bravia-tvos@beta`

**Comment by Paden** [comment]
Yes, now I see `Service Methods "getPlayingContentInfo" not known!` happen over and over now.

- Changing Apps does not work. I get a "Service Methods "setActiveApp" not known!" message for those.
- Changing Inputs does not work. I get a "Service Methods "setPlayContent" not known!" there.

**Comment by SeydX** [comment]
@Paden 

is the TV turned on during the action?

**Comment by Paden** [comment]
Yes, it is. The turn on, Back, and Volume control all still work.

**Comment by SeydX** [comment]
v5.0.6-beta.7 is online

``sudo npm i -g homebridge-bravia-tvos@beta``

**Comment by Paden** [comment]
Hey check that out! Apps and Inputs both work now! Well done!

**Comment by SeydX** [comment]
Puhh, very nice 😄
